<?php 

$list_sku = json_decode('[
    {
      "COD_COMERCIAL": "CGR001",
      "EAN": 7896083410552,
      "DESCRICAO_SAP": "COGNITUS 225 MG 60 CPR",
      "FAMILIA": "COGNITUS",
      "UNID_CAIXA": 24,
      "FUNCAO":"FITOTERÁPICO SIMPLES. OUTROS PRODUTOS QUE ATUAM SOBRE O SISTEMA NERVOSO. <br>TRATAMENTO DE DISTÚRBIOS DE MEMÓRIA PELO PROCESSO FISIOLÓGICO DO ENVELHECIMENTO. "
    },
    {
      "COD_COMERCIAL": "CGT001",
      "EAN": 7896083410552,
      "DESCRICAO_SAP": "COGNITUS 225MG 60 CPR",
      "FAMILIA": "COGNITUS",
      "UNID_CAIXA": 24
    }
  ]', true);

?>