<?php 

$list_sku = json_decode('[
    {
      "COD_COMERCIAL": "REN001",
      "EAN": 7898328480030,
      "DESCRICAO_SAP": "RENAGEL - 800 MG COM REV FR PLA X 180 GZ",
      "FAMILIA": "RENAGEL",
      "UNID_CAIXA": 12,
      "FUNCAO":"CONTROLE DO FÓSFORO SÉRICO EM PACIENTES COM DOENÇA RENAL CRÔNICA (DRC) SOB DIÁLISE"
    },
    {
      "COD_COMERCIAL": "REN001",
      "EAN": 7898328480030,
      "DESCRICAO_SAP": "RENAGEL - 800 MG COM REV FR PLA X 180 GZ",
      "FAMILIA": "RENAGEL",
      "UNID_CAIXA": 12,
      "FUNCAO":"CONTROLE DO FÓSFORO SÉRICO EM PACIENTES COM DOENÇA RENAL CRÔNICA (DRC) SOB DIÁLISE"
    }
  ]', true);

?>